import "./globals.css";
import type { Metadata } from "next";
// import { Inter } from "next/font/google";
import { DM_Sans } from "next/font/google";
import { Providers } from "./provider";
import NavBar from "@/components/NavBar/page";

const dmSans = DM_Sans({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="h-[100%]">
      <body className={dmSans.className} style={{height: '100%'}}>
        <Providers>
          <div className="h-[100%]">
            <NavBar />
            <div>{children}</div>
          </div>
        </Providers>
      </body>
    </html>
  );
}
